### ISSUE TITLE
package.json jest config not respected

### ISSUE THREAD

**Issue by Neitsch** [stryker-mutator/stryker-jest-runner#24]
Hi,

I've been trying to add Stryker to my project, but have been hitting several bumps along the way. Right now I think the issue comes from jest:
I'm using Enzyme for my tests. This requires me to have setupFiles configured for jest in package.json (https://facebook.github.io/jest/docs/en/configuration.html#setupfiles-array). It does not appear that those files are called, since enzyme throws an error.

An easy way to reproduce is something like this:
```
// __tests__/my-test.js
it('dummy', () => expect(setup).toBe(true))

// package.json
{
...
"jest": {"setupFiles": ["<rootDir>/setup.js"]}
...
}

// setup.js
global.setup = true;

//src.js
if(1 == 1) {
  console.log("ABC")
}
```

Expected: Test reports mutants survived (jest test passes)
Actual: ReferenceError: setup is not defined

**Comment by mthmulders** [comment]
Thanks for the report! Indeed, when used with Stryker, Jest will be invoked using [some default options](https://github.com/stryker-mutator/stryker-jest-runner/blob/2d24af4cc656d7df7eaf6e7a64bb6748b3e00fe4/src/JestTestRunner.ts#L13). 

To have this working, we would need to obtain the Jest configuration [in the same manner as Jest itself does](https://github.com/facebook/jest/blob/d1845116ebe818e6d945d50ad4857752758970ee/packages/jest-cli/src/cli/index.js#L215) but that method is currently not exported.

**Comment by Archcry** [comment]
Should be resolved in https://github.com/stryker-mutator/stryker-jest-runner/pull/25
