### ISSUE TITLE
Error: Cannot find module './myComponent.component.js' - Trouble with require()

### ISSUE THREAD

**Issue by Floriangomis** [stryker-mutator/stryker-jest-runner#28]
Hi all,

Currently I am facing some problems with this plugin. 

I guess I configured everything correctly : 
```
module.exports = function(config) {
  config.set({
    files: [
      "./directory/desktop/app/components/myComponent/myComponent.test.js",
    ],
    testRunner: "jest",
    mutator: "javascript",
    transpilers: [],
    reporter: ["html", "clear-text", "progress"],
    coverageAnalysis: "off"
  });
};
```

When I execute my unit test via gulp it works pretty fine but when I executed 

`node_modules/.bin/stryker run`

here is what I get : 

```
[2018-01-30 14:46:37.091] [ERROR] InitialTestExecutor - One or more tests resulted in an error:
        Error: Cannot find module './myComponent.component.js' from 'myComponent.test.js'
[2018-01-30 14:46:37.092] [ERROR] StrykerCli - an error occurred Error: Something went wrong in the initial test run
```

Is there anything wrong by using require that I am missing ? Also if I remove this require then the error is that angular is not defined so I was wondering if jest.init.js were exectuted at some point ? ( Which is for me the same problem because in jest.init.js I am mainly importing module via require().

Thanks in advance ;-)

**Comment by mthmulders** [comment]
Thanks for reporting this!
I'm assuming that `jest.init.js`is a file that you wrote, and that it is referenced from the Jest configuration? If that is the case, no Stryker will (currently) not use it.
I'm saying *currently*, because @Archcry is currently working on a rework of this project. I think his implementation *will* use custom Jest configuration. You can follow his work in #25.

**Comment by Floriangomis** [comment]
Thank you for the reply,
Yes I think we can close this issue. Someone explained me this yesterday on Gitter.
I Finally make it works with Mocha !
