### ISSUE TITLE
Default jest config file jest.config.js is ignored.

### ISSUE THREAD

**Issue by andy128k** [stryker-mutator/stryker-jest-runner#31]

**Comment by simondel** [comment]
Thanks for opening this issue! Could you please post your stryker.conf.js?

**Comment by andy128k** [comment]
This works

```js
module.exports = function(config) {
  config.set({
    files: [
      { pattern: "assets/**/*.js", mutated: true, included: false },
    ],
    testRunner: "jest",
    mutator: "javascript",
    transpilers: ["babel"],
    reporter: ["html", "baseline", "clear-text", "progress"],
    coverageAnalysis: "off",
    babelrcFile: ".babelrc",
    jest: {
        project: 'default',
        config: require(__dirname + '/jest.config.js')
    },
    "logLevel": "all",
  });
};
```

but this doesn't

```js
module.exports = function(config) {
  config.set({
    files: [
      { pattern: "assets/**/*.js", mutated: true, included: false },
    ],
    testRunner: "jest",
    mutator: "javascript",
    transpilers: ["babel"],
    reporter: ["html", "baseline", "clear-text", "progress"],
    coverageAnalysis: "off",
    babelrcFile: ".babelrc",
//    jest: {
//        project: 'default',
//        config: require(__dirname + '/jest.config.js')
//    },
    "logLevel": "all",
  });
};
```

**Comment by simondel** [comment]
That the expected behavior. If you don't specify anything related to your jest config, the plugin will look for a jest config in your package.json. If you want to require a file, you will have to do that with the config you provided here.

How do you suggest we make this clearer in the README for this package? Or perhaps combined with more extensive logging?

**Comment by andy128k** [comment]
But `jest.config.js` is recognized by Jest itself.

**Comment by simondel** [comment]
Good point! If Jest can find it by default, I would expect Stryker to find it as well by default. What are your thoughts @Archcry ?

**Comment by Archcry** [comment]
According to the [Configuring Jest](https://facebook.github.io/jest/docs/en/configuration.html) page you can indeed choose to specify the jest configuration in the jest.config.js. It seems like jest is trying to load the package.json first and then tries to fall back on the jest.config.js. I think we can replicate this functionality in Stryker by trying to load the package.json config first and if that does not succeed load the jest.config.js.

The page does not explicitly state which config is tried first though, thoughts on that?

**Comment by nicojs** [comment]
@Archcry, try it out with a lottle expiriment? :)

**Comment by simondel** [comment]
It first looks for `jest.config.js` and then it will look in your `package.json` for a `jest` property. 
I tested this with:
```js
// jest.config.js
module.exports = {
    verbose: true,
};
```
And package.json:
```
"scripts": {
    "test": "jest"
  },
"jest": {
    "collectCoverage": true,
    "collectCoverageFrom": [
      "sum.js"
    ],
    "coverageDirectory": "./coverage"
  }
```

The result was a Jest run without coverage. If I remove the `jest.config.js` file I do get a coverage result from Jest.
