### ISSUE TITLE
Override jest config settings

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-jest-runner#32]
Right now, the Jest config of the user is used without making any changes. I believe we should make some changes to speed up the stryker-jest-runner

| Config setting | Default value | Suggest value | Reason |
| --------------- | ------------ | -------------| -------------|
| bail | `false` | `true` | As soon as a single test fails, we can stop testing. In the best case, we run 1 test. In the worst case we still run *'n'* tests. We also do this with Mocha. |
| collectCoverage | `false` | `false` | We don't need to collect coverage since we don't have a test framework plugin for Jest. |
| verbose | `false` | `false` | Verbose logging slows down the test run. |

All config options: https://facebook.github.io/jest/docs/en/configuration.html

**Comment by mthmulders** [comment]
Makes sense to me. The second one (`collectCoverage`) is still on the wishlist though. As I understood from @nicojs, it would enable more efficient runs. But that should definitely be a different issue.

**Comment by nicojs** [comment]
Agreed, that should be a different issue.

**Comment by Archcry** [comment]
We'll disable test coverage for now and enable it when we implement test coverage within the Stryker-jest-runner. Should there be an option on the jest config object in the Stryker config to control this?

**Comment by simondel** [comment]
No, the stryker-jest-runner should always override this setting

**Comment by Archcry** [comment]
Alright

**Comment by simondel** [comment]
@Archcry We may also want to override this setting: https://facebook.github.io/jest/docs/en/configuration.html#testresultsprocessor-string

**Comment by nicojs** [comment]
Fixed with #34 and released in version `0.5`
