### ISSUE TITLE
Failed to update from 0.3.0

### ISSUE THREAD

**Issue by unlight** [stryker-mutator/stryker-jest-runner#37]
I've tried to update `stryker-jest-runner` from 0.3.0 to latest `0.5.1`, and got error:

```
[2018-03-09 16:27:12.818] [ERROR] InitialTestExecutor - One or more tests resulted in an error:
        : ? Validation Error:

  Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

? Validation Error:

  Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

[2018-03-09 16:27:12.819] [ERROR] StrykerCli - an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (D:\My\Dev\nest-typescript-starter\node_modules\stryker\src\process\InitialTestExecutor.js:98:15)
    at InitialTestExecutor.<anonymous> (D:\My\Dev\nest-typescript-starter\node_modules\stryker\src\process\InitialTestExecutor.js:33:30)
    at step (D:\My\Dev\nest-typescript-starter\node_modules\tslib\tslib.js:133:27)
    at Object.next (D:\My\Dev\nest-typescript-starter\node_modules\tslib\tslib.js:114:57)
    at fulfilled (D:\My\Dev\nest-typescript-starter\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Tried to update to `0.4.0` and got same error.
Version `0.3.0` worked without errors.

stryker.config.js
```
    config.set({
        files: [
            { pattern: 'app/**/*.graphql', included: false, mutated: false },
        ],
        testRunner: 'jest',
        mutator: 'typescript',
        transpilers: ['typescript'],
        reporter: ['html', 'clear-text', 'progress'],
        coverageAnalysis: 'off',
        tsconfigFile: 'tsconfig.json',
        jest: {
            project: 'default',
            config: require('./jest.config'),
        },
        mutate: [
            'app/**/cat.controller.ts',
        ],
        timeoutMs: 10 * 1000,
        // timeoutFactor: 2,
        htmlReporter: {
            baseDir: '.testresults/mutation'
        },
        logLevel: 'debug',
    });
```

jest.config.js
```
module.exports = {
    "testEnvironment": "node",
    "transform": {
        "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "collectCoverage": false,
    "coverageDirectory": ".testresults",
    "coverageReporters": [
        "lcov",
        "text",
    ],
    "collectCoverageFrom": [
        "app/**/*.ts",
        "!app/**/*.spec.ts",
        "!app/**/*.ispec.ts"
    ],
    "testMatch": [
        "<rootDir>/app/**/*.spec.ts"
    ],
    "moduleFileExtensions": [
        "ts",
        "js"
    ]
};

```

**Comment by Archcry** [comment]
Versions newer than version 0.3.0 use a new implementation for the jest-runner. The newer versions use the config defined in either your `jest.config.js` or your `package.json` (in that order). The error message you're getting suggests you are missing the `ts-jest` package in your node modules folder.

`Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.`

Is your project on GithHub by any chance? Or are you able to make a repository that reproduces your issue so I can take a look at it?

**Comment by unlight** [comment]
`ts-jest` is in node_modules, maybe it's wrong path for some reason.

> Is your project on GithHub by any chance? 

Yes.

```
git clone https://github.com/unlight/nest-typescript-starter
cd nest-typescript-starter
git checkout -f jest_update
npm install
npm run test:m
```

**Comment by Archcry** [comment]
I made a pul-request on your jest branch with the working stryker config for the new jest runner. A couple of things:

You don't really have to provide options for jest in your particular Stryker config anymore (the project property defaults to `default` and your `jest.config.js` is automatically loaded when no config property is provided). You also specified that you wanted to use the typescript transpiler, this is not needed because the typescript is handled by jest (so no need to transpile it before sending it to jest). Last but not least, I added the `ts-jest` package to the included files in the stryker.conf.js so it is available in the sandbox Stryker uses.

Good luck with your project!

**Comment by nicojs** [comment]
Cool @Archcry 

Just one question, why is this needed: `'node_modules/ts-jest/**/*.js'`? Is it a limitation of ts-jest somehow? That should not be needed right?

How is it handling transpile errors here? I would think it is reported as runtime errors.

**Comment by Archcry** [comment]
> Just one question, why is this needed: 'node_modules/ts-jest/**/*.js'? Is it a limitation of ts-jest somehow? That should not be needed right?

I don't know to be honest, I guess it tries to load it specifically from the projectroot that is set to the sanbox.
`<rootDir>/node_modules/ts-jest/preprocessor.js`

> How is it handling transpile errors here? I would think it is reported as runtime errors. (I guess I had 2 questions after all ;))

I think it will report as failed with failuremessages telling Stryker that it failed to transpile input files.
