### ISSUE TITLE
JestConfigEditor test failing

### ISSUE THREAD

**Issue by mthmulders** [stryker-mutator/stryker-jest-runner#39]
When working on #38, I noticed that one test case is currently failing. It fails not only on my machine, but also [on Travis](https://travis-ci.org/stryker-mutator/stryker-jest-runner/jobs/361525669):

        1) Integration JestConfigEditor
            should create a jest configuration for a react project:

            AssertionError: expected { Object (collectCoverageFrom, setupFiles, ...) } to deeply equal { Object (collectCoverageFrom, setupFiles, ...) }
            + expected - actual

                "src/**/*.{js,jsx,mjs}"
                ]
                "moduleFileExtensions": [
                "web.js"
            +    "mjs"
                "js"
                "json"
                "web.jsx"
                "jsx"
                "node"
            -    "mjs"
                ]
                "moduleNameMapper": {
                "^react-native$": "react-native-web"
                }

**Comment by nicojs** [comment]
For me locally as well. I'll create the PR
