### ISSUE TITLE
Move to monorepo

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-jest-runner#43]
@mthmulders is it time to move? Moving to the mono repo will help with keeping the stryker-jest-runner up-to-date with the latest stryker releases. It will also help with issue tracking amongst others.

**Comment by nicojs** [comment]
We'll also make you a full contributor if you're not already :)

**Comment by mthmulders** [comment]
Fine with me. Maybe @Archcry also has a say in this?

**Comment by Archcry** [comment]
Ye I am fine with this :D
