### ISSUE TITLE
jest and NODE_ENV environment variable

### ISSUE THREAD

**Issue by unlight** [stryker-mutator/stryker-jest-runner#50]
When I run jest my process.env.NODE_ENV is equal to `test`.
But when I run mutation test it is not equal to `test` (it's `undefined`)

**Comment by unlight** [comment]
https://github.com/facebook/jest/blob/master/packages/jest-cli/bin/jest.js#L12-L14

**Comment by simondel** [comment]
Nice find! We can fix this :)
