### ISSUE TITLE
jest runner not registering as a plugin correctly

### ISSUE THREAD

**Issue by mshogren** [stryker-mutator/stryker-jest-runner#8]
The plugin is loaded as shown here

    [2017-02-12_ 11:00:47.051] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner (matched with expression stryker-*)
    [2017-02-12 11:00:47.054] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner

However this error follows

    Error: Could not find a testrunner with name jest, did you install it correctly (for example: npm install --save-dev stryker-jest-runner)?
        at TestRunnerFactory.Factory.create

I believe this is due to this in index.ts

    TestRunnerFactory.instance().register('jest-test-runner', JestTestRunner);

That should be

    TestRunnerFactory.instance().register('jest', JestTestRunner);

**Comment by mthmulders** [comment]
Seems legit. I changed it, will be fixed in the next release. Thanks for reporting!
