### ISSUE TITLE
Jest runner not returning empty error messages as strings

### ISSUE THREAD

**Issue by mshogren** [stryker-mutator/stryker-jest-runner#9]
I am getting the following error in IsolatedTestRunnerAdapterWorker.reportResult

[2017-02-12 11:20:21.035] [ERROR] Stryker - One or more tests errored in the initial test run:
      TypeError: Cannot read property 'toString' of undefined

The Jest runner is returning an array of undefined when the are no test failures.

**Comment by mshogren** [comment]
I think this probably should be fixed in the IsolatedTestRunnerAdapterWorker.reportResult function as well. It attempts to turn error objects into strings already but fails where the error is undefined and probably if it is null too.

**Comment by mthmulders** [comment]
The [Karma test runner](https://github.com/stryker-mutator/stryker-karma-runner/blob/master/src/KarmaTestRunner.ts#L114) only returns error messages when there actually are some. If there are non, its `errorMessages` is [an empty array](https://github.com/stryker-mutator/stryker-karma-runner/blob/master/src/KarmaTestRunner.ts#L181).

I think the Jest runner should behave accordingly. @nicojs, do you agree with that?

**Comment by nicojs** [comment]
@mthmulders yes your probably correct. However, maybe we should also try to make Stryker resilient against this error. If @mshogren is correct than the error appears in this code:

```typescript
 result.errorMessages = result.errorMessages.map((error: any) => {
        if (error instanceof Error && error.stack) {
            return `${error.name}: ${error.message}\n${error.stack.toString()}`;
        } else {
          return error.toString();
        }
      });
```

So i think that right now the `errorMessages` is filled with an `undefined` value. Should we be resilient against this?

**Comment by mthmulders** [comment]
@nicojs If we follow the golden "never trust your inputs" rule, then I think it should indeed be fixed in Stryker itself.
Apart from that it might be a good think if all plugins work more-or-less the same way. Returning an array with only non-null, defined values is a one-liner. I can fix that anyway, OK?

**Comment by simondel** [comment]
We should be resilient, but we should also turn on the explicit null checks for the `stryker-karma-runmer`
